AWSTemplateFormatVersion: "2010-09-09"
Description: OTT Search Analytics team in datalake domain, dev environment

Parameters:
  pPipelineReference:
    Type: String
    Default: none

Resources:
  rOtt:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "{{resolve:ssm:/sdlf/team/main}}"
      Parameters:
        pPipelineReference: !Ref pPipelineReference
        pTeamName: ott
        pStorageDeploymentInstance: dev
