baseURL = "https://thanhtrung102.github.io/ott-sdlf/"
relativeURLs = true
canonifyURLs = true

theme = "hugo-theme-learn"
contentDir = "docs"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = "OTT Search Analytics Pipeline — AWS SDLF FCJ Workshop"
  author = ""
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[Languages]
[Languages.en]
title = "OTT Search Analytics Pipeline"
weight = 1
languageName = "English"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
