AWSTemplateFormatVersion: "2010-09-09"
Description: OTT searchevents Stage B — Glue ETL enrichment (schedule + Stage A event)

Parameters:
  pPipelineReference:
    Type: String
    Default: none

Resources:
  rMainB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "{{resolve:ssm:/sdlf/stageglue/main}}"
      Parameters:
        pPipelineReference: !Ref pPipelineReference
        pDeploymentInstance: ott-mainB
        pStorageDeploymentInstance: prod
        pDatasetDeploymentInstance: searchevents
        pGlueJobName: sdlf-ott-searchevents-glue-job
        pGlueNumberOfWorkers: 10
        pGlueWorkerType: G.1X
        pTriggerType: event
        pEventPattern: >-
          {
            "source": ["aws.states"],
            "detail-type": ["Step Functions Execution Status Change"],
            "detail": {
              "status": ["SUCCEEDED"],
              "stateMachineArn": ["{{resolve:ssm:/sdlf/pipeline/rStateMachine/ott-mainA}}"]
            }
          }
        pSchedule: "cron(0 19 * * ? *)"
        pEnableTracing: "false"
        pGlueArguments: >-
          {
            "--job-bookmark-option": "job-bookmark-enable",
            "--enable-metrics": "",
            "--SOURCE_LOCATION": "s3://{{resolve:ssm:/sdlf/storage/rRawBucket/prod}}/ott/searchevents/",
            "--OUTPUT_LOCATION": "s3://{{resolve:ssm:/sdlf/storage/rAnalyticsBucket/prod}}/ott/searchevents/curated/",
            "--PUSH_DOWN_PREDICATE": "all"
          }
